### ISSUE TITLE
日本語入力（中国語入力）を使えるようにしたい

### ISSUE THREAD

**Issue by itohdak** [line-school2018summer/Tokyo_A_Client#7]

**Comment by yykk3322** [comment]
エミュレータ内のSettingsでデバイスの言語設定を変更することで入力できました

**Comment by itohdak** [comment]
（画像例とかくっつけると良いかも？）

**Comment by itohdak** [comment]
まんま[これ](https://qiita.com/na3ksg/items/9b57f032158e76615ae9)ですね
